---
language: "python"
python:
- 2.7

env:
- ANSIBLE_VERSION=2.9
  PHP_VERSION=7.4
- ANSIBLE_VERSION=2.9
  PHP_VERSION=7.3
- ANSIBLE_VERSION=2.9
  PHP_VERSION=7.2

before_install:
# Make sure everything's up to date.
- sudo apt-get update -qq

install:
- pip install ansible==$ANSIBLE_VERSION
- "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
- "ansible-playbook -i tests/travis-inventory tests/travis-playbook.yml --syntax-check"
- "ansible-playbook -i tests/travis-inventory tests/travis-playbook.yml --connection=local --sudo"
- >
  ansible-playbook -i tests/travis-inventory tests/travis-playbook.yml --connection=local --sudo
  | grep -q 'changed=0.*failed=0'
  && (echo 'Idempotence test: pass' && exit 0)
  || (echo 'Idempotence test: fail' && exit 1)
- >
  curl http://localhost/
  | grep -q 'Welcome to nginx!'
  && (echo 'NGINX test: pass' && exit 0)
  || (echo 'NGINX test: fail' && exit 1)
- >
  if [ -S /var/run/php7.4-fpm.sock ]; then
    echo 'PHP5-FPM Socket exists: pass' && exit 0
  else
    echo 'PHP5-FPM Socket exists: fail' && exit 1
  fi

- >
  stat -c "%a:%U:%G" "/var/run/php${PHP_VERSION}-fpm.sock"
  | grep -q '660:root:www-data'
  && (echo 'PHP5-FPM Socket permissions: pass' && exit 0)
  || (echo 'PHP5-FPM Socket permissions: fail' && exit 1)

